kind: pipeline
type: docker
name: test

steps:
  - name: initial project
    image: room_php
    pull: never
    commands:
      - composer update
      - cp .env.example .env
      - php artisan key:generate
      - php artisan jwt:secret -f   
  - name: testing
    image: room_php
    environment:
      TELEGRAM_LOGGER_BOT_TOKEN:
        from_secret: TELEGRAM_LOGGER_BOT_TOKEN
      TELEGRAM_LOGGER_CHAT_ID=:
        from_secret: TELEGRAM_LOGGER_CHAT_ID
    pull: never
    commands:
      - php artisan test
