kind: pipeline
type: docker
name: test

steps:
  - name: initial project
    image: room_php
    pull: never
    commands:
      - composer update
      - cp .env.example .env
      - php artisan key:generate
      - php artisan jwt:secret -f   
  - name: testing
    image: room_php
    pull: never
    commands:
      - php artisan test
