kind: pipeline
type: docker
name: test

steps:
 - name: backend
   image: room_php
   pull: never
   commands:
    - composer update
    - cp .env.example .env
    - php artisan jwt:secret
    - php artisan test
