version: '3.8'
services:
 drone-server:
  image: drone/drone:2
  container_name: drone-server
  ports:
   - 89:80
   - 449:443
  restart: always
  volumes:
   - ./drone:/data
  environment:
   DRONE_GITHUB_CLIENT_ID: 0bcd44dc5f53c2b8e295
   DRONE_GITHUB_CLIENT_SECRET: 33c0c53e858181cc653d8aec22e5d3daa682c2f6
   DRONE_RPC_SECRET: a72e5b4e35f612dfd9bb6b0508f00cef
   DRONE_SERVER_HOST: dd46-2001-b011-8010-1311-8ebc-dd82-318d-632e.ngrok-free.app
   DRONE_SERVER_PROTO: https
   DRONE_LOGS_DEBUG: 'true'
   DRONE_LOGS_TRACE: 'true'

 drone-runner:
  image: drone/drone-runner-docker:1
  container_name: drone-runner
  ports:
   - 3000:3000
  restart: always
  depends_on:
    - drone-server
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
   DRONE_RPC_HOST: dd46-2001-b011-8010-1311-8ebc-dd82-318d-632e.ngrok-free.app
   DRONE_RPC_PROTO: https
   DRONE_RPC_SECRET: a72e5b4e35f612dfd9bb6b0508f00cef
   DRONE_RUNNER_CAPACITY: 2
   DRONE_RUNNER_NAME: drone-runner 
   DRONE_LOGS_TRACE: 'true'