version: "3.8"

services:

 drone-server:
  container_name: drone-server
  image: drone/drone:2
  ports:
   - 90:80
   - 449:443
  restart: always
  volumes:
   - ./storage/app/public:/var/lib/drone
  environment:
   DRONE_GITHUB_CLIENT_ID: 136b488e86a11d7c532a
   DRONE_GITHUB_CLIENT_SECRET: 4ec1059bd50e79dbd5b9d46b76cd0eb26794ee37
   DRONE_RPC_SECRET: 4ec1059bd50e79dbd5b9d46b76cd0eb26794ee37
   DRONE_SERVER_HOST: 34.81.135.235:90
   DRONE_SERVER_PROTO: http

 drone-runner:
  image: drone/drone-runner-docker:1
  container_name: drone-runner
  restart: always
  depends_on:
    - drone-server
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
   DRONE_RPC_HOST: drone-server
   DRONE_RPC_PROTO: http
   DRONE_RPC_SECRET: 4ec1059bd50e79dbd5b9d46b76cd0eb26794ee37
   DRONE_RUNNER_CAPACITY: 2

